### ISSUE TITLE
[SfM] Control Points coarse registration

### ISSUE THREAD

**Issue by pmoulon** [openMVG/openMVG#328]
Add ability to "geo-"register a scene by using Ground Control Points (GCPs).
- Consider only a coarse registration for the moment.
```
// registration (coarse):
// - compute the 3D points corresponding to the control point observation for the SfM scene
// - compute a coarse registration between the controls points & the triangulated point
// - transform the scene according the found transformation
```

**Definition:**
- GCP are a 3D point with known 3D coordinates and known 2D image observations.
By computing the transformation between the triangulation of the observations for a given SfM scene and the ground truth 3D known positions it allows to setup the scene in the desired coordinates system (i.e. ability to take metric measures)

**Note on GCPs:**

- A minimum of 3 GCPs are required to compute a registration.
- GCPs should be clicked in at least 2 images each.
- More GCPs do not contribute significantly to an increase in accuracy, but use a bit more than 3 is recommend => 4-5.
- I recommend to identify (add image observation of a GCP) in many images, since the triangulation of the GCP will be more reliable if seen with convergent view angles. Using more observations help to minimizes the measurements inaccuracies and helps to detect mistakes. 
- The GCPs should be placed evenly on the geometry to minimize the error of the computed registration..

**Tasks:**
- [x] allow sfm_data container to support Control_Points => stored as Landmarks
  - introduce a version 0.2 of the file
- [x] design a UI (graphical User Interface) 
   - allow to set the control points image observations and 3D control points coordinates.
- [x] add a Similarity3 class in openMVG::geometry module
  - handle S[R|C] transform on 3D points and Pose3 objects.
- [x] Compute the registration based on the control_points 3D coords and the control_points triangulations.
- [x] Display some statistics about the registration:
  - residual errors of the triangulation,
  - CP registration error

- [x] Add an UI to type the 3D coordinates of the GCP (Ground Control Points)
![image](https://cloud.githubusercontent.com/assets/3235050/10071245/977cd10e-62b8-11e5-8a47-96ef884fa0f7.png)
- [x] Allow to remove some GCP from the GUI list

- [x] Add some help or a short tutorial related to this feature
- [x] Display a small report about registration accuracy (per control points)
![image](https://cloud.githubusercontent.com/assets/3235050/10187606/e3f8d168-6759-11e5-92b0-3b808dd710fd.png)

- [x] Add a brief doc in a About menu.
